
trigger: none

pool:
  vmImage: 'windows-latest'

steps:

- task: CmdLine@2
  inputs:
    script: |
      set DRIVERPATH=%ChromeWebDriver%
      set

- task: CmdLine@2
  inputs:
    script: |
      set

#- task: UseDotNet@2
#  inputs:
#    packageType: 'sdk'
#    version: '2.2.402'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'test'
#    projects: 'WolframNet'

#- task: SpecFlowReportGenerator@1
#  displayName: 'Generate SpecFlow Report'
#  inputs:
#    projectFile: '**/WolframNet.Features.csproj'
