trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo google-chrome --product-version
      version=$(google-chrome --version | grep -iE "[0-9.]{10,20}")
      echo $version


#      wget "https://chromedriver.storage.googleapis.com/${version}/chromedriver_linux64.zip"
#      unzip chromedriver_linux64.zip
#      chmod +x chromedriver
      
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'test'
#    projects: 'WolframNet'
#