trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      wget https://chromedriver.storage.googleapis.com/75.0.3770.140/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      chmod +x chromedriver
  displayName: 'Install Chrome Driver'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'WolframNet'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
