trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.402'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      google-chrome --version
      CHROMEDRIVER='https://chromedriver.storage.googleapis.com/`google-chrome --version`/chromedriver_linux64.zip'
      wget ${CHROMEDRIVER}
      unzip chromedriver_linux64.zip
      chmod +x chromedriver
      
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'WolframNet'